global_costmap:
  plugins:
    - { name: static_layer,                  type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer,               type: "costmap_2d::InflationLayer" }
  static_layer:
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    map_topic: map
    first_map_only: false
    subscribe_to_updates: false
    track_unknown_space: true
    use_maximum: false
    trinary_costmap: true
  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
  footprint: [ [ -0.325, -0.325 ], [ -0.325, 0.325 ], [ 0.325, 0.325 ], [ 0.325, -0.325 ] ]
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 1.5
  rolling_window: true
  width: 10
  height: 10
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.05


local_costmap:
  plugins:
    - { name: obstacle_layer,        type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      topic: scan
      sensor_frame: laser
      observation_persistence: 0.0
      expected_update_rate: 0.0
      data_type: LaserScan
      clearing: true
      marking: true
      max_obstacle_height: 1.0
      min_obstacle_height: 0.0
      obstacle_range: 2.5
      raytrace_range: 3.0
      inf_is_valid: false
    track_unknown_space: true
    footprint_clearing_enabled: true
    combination_method: 1

  inflation_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 5.0
  footprint: [ [ -0.325, -0.325 ], [ -0.325, 0.325 ], [ 0.325, 0.325 ], [ 0.325, -0.325 ] ]
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 1.5
  rolling_window: true
  width: 10
  height: 10
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.05

BaseGlobalPlanner:
  use_grid_path: false
  use_quadratic: true
  use_dijkstra: true
  allow_unknown: true
  default_tolerance: 0.2
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1
  outline_map: true

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 0.3
  acc_lim_y: 0
  acc_lim_th: 0.1

  max_vel_x: 0.26
  min_vel_x: -0.26
  max_vel_y: 0
  min_vel_y: 0

  max_vel_trans: 0.26
  min_vel_trans: 0.05
  max_vel_theta: 0.26
  min_vel_theta: 0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false        # If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.

 # Forward Simulation Parameters
  sim_time: 4.0                         # The amount of time to forward-simulate trajectories in seconds
  sim_granularity: 0.025                # The step size, in meters, to take between points on a given trajectory
  vx_samples: 20                        # The number of samples to use when exploring the x velocity space
  vy_samples: 0                         # The number of samples to use when exploring the y velocity space
  vth_samples: 40                       # The number of samples to use when exploring the theta velocity space
  controller_frequency: 5.0 
  
  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Global Plan Parameters
  prune_plan: false
