global_costmap:
  plugins:
    - { name: static_layer,                  type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer,               type: "costmap_2d::InflationLayer" }
  static_layer:
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    map_topic: map
    first_map_only: false
    subscribe_to_updates: false
    track_unknown_space: true
    use_maximum: false
    trinary_costmap: true
  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
  footprint: [ [ -0.325, -0.325 ], [ -0.325, 0.325 ], [ 0.325, 0.325 ], [ 0.325, -0.325 ] ]
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  rolling_window: true
  width: 10
  height: 10
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.05


local_costmap:
  plugins:
    - { name: obstacle_layer,        type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      topic: scan
      sensor_frame: laser
      observation_persistence: 0.0
      expected_update_rate: 0.2
      data_type: LaserScan
      clearing: true
      marking: true
      max_obstacle_height: 1.0
      min_obstacle_height: 0.0
      obstacle_range: 2.5
      raytrace_range: 3.0
      inf_is_valid: false
    track_unknown_space: true
    footprint_clearing_enabled: true
    combination_method: 1

  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
  footprint: [ [ -0.325, -0.325 ], [ -0.325, 0.325 ], [ 0.325, 0.325 ], [ 0.325, -0.325 ] ]
  update_frequency: 10
  publish_frequency: 10
  transform_tolerance: 0.5
  rolling_window: true
  width: 10
  height: 10
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.05

